// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Basic fallback to prevent crash on load if keys are missing
// The console error will help debugging, but the app might at least render the error boundary.
const fallbackUrl = "https://placeholder.supabase.co";
const fallbackKey = "placeholder";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("Supabase keys are missing! Check your .env file. Using fallbacks to prevent immediate crash.");
}

export const supabase = createClient<Database>(
  SUPABASE_URL || fallbackUrl,
  SUPABASE_PUBLISHABLE_KEY || fallbackKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
